---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Товары в корзине пользователя должны сохраняться даже после выхода из интернет-магазина
  - "Необходимо продумать логику фильтрации, по какому принципу будет осуществляться фильтрация: по одной характеристике или нескольким, какие они будут"
  - Фильтрацию товаров можно отменить без перезагрузки страницы 
  - Сайт должен одинакого функционировать на всех доступных для выбора языках
  - Информация о товаре (название, рейтинг, цена со скидкой и без нее) в каталоге не может отличаться от информации о том же товаре в корзине или заказе 
  - Пользователь должен иметь возможность продолжать просматривать товары после добавления товара в корзину
  - Удаленный из корзины товар не может заново отображаться в корзине или заказе 
  

  
