---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Товары в корзине пользователя должны сохраняться даже после выхода из интернет-магазина
  - "Необходимо продумать логику фильтрации, по какому принципу будет осуществляться фильтрация: по одной характеристике или нескольким, какие они будут"
  - Фильтрацию товаров можно отменить без перезагрузки страницы 
  - Сайт должен одинакого функционировать на всех доступных для выбора языках
  

  
